server:
  port: 3000

spring:
  application:
    name: file-service

  # 데이터베이스 연결 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.url}
    username: ${db.username}
    password: ${db.password}

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: ${ddl.auto}
  # 파일 업로드 용량 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 60MB
      file-size-threshold: 20MB

# 파일 업로드 경로 설정
file:
  upload:
    url: ${file.url}
    path: ${file.path}

# 로거 설정
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace


